//! CR 732.2a: every read of a recorded period's classification answers on the blink boards and on
//! a restored offer as it did at this row's base.
//!
//! The rows are the reads the reader census returns, regenerated by
//! `git grep -nP '(?<![a-z_])loop_period_(controller|driver|is_priority_driven)(_of)?\s*\(' -- crates/engine/`
//! and classified there as a definition, a read, or text. Each read is asked through the
//! test-support wrapper of the accessor it names, never re-derived here.

use engine::game::scenario::{GameRunner, P0};
use engine::types::ability::TargetRef;
use engine::types::actions::GameAction;
use engine::types::game_state::{
    loop_period_controller_of_for_tests, loop_period_driver_of_for_tests,
    loop_period_is_priority_driven_of_for_tests, CastPaymentMode, GameState, LoopActionContext,
    LoopDetectionMode, StackEntryKind, WaitingFor,
};
use engine::types::identifiers::ObjectId;
use engine::types::player::PlayerId;

/// The six classification accessors' answers on one state, the `_of` forms asked of its record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Answers {
    pub(crate) controller: Option<PlayerId>,
    pub(crate) priority_driven: bool,
    pub(crate) driver: Option<PlayerId>,
    pub(crate) controller_of: Option<PlayerId>,
    pub(crate) priority_driven_of: bool,
    pub(crate) driver_of: Option<PlayerId>,
}

pub(crate) fn answers(state: &GameState) -> Answers {
    let record = &state.last_loop_action_sequence;
    Answers {
        controller: state.loop_period_controller_for_tests(),
        priority_driven: state.loop_period_is_priority_driven_for_tests(),
        driver: state.loop_period_driver_for_tests(),
        controller_of: loop_period_controller_of_for_tests(record),
        priority_driven_of: loop_period_is_priority_driven_of_for_tests(record),
        driver_of: loop_period_driver_of_for_tests(record),
    }
}

impl std::fmt::Display for Answers {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "controller={:?} priority_driven={} driver={:?} controller_of={:?} \
             priority_driven_of={} driver_of={:?}",
            self.controller,
            self.priority_driven,
            self.driver,
            self.controller_of,
            self.priority_driven_of,
            self.driver_of
        )
    }
}

#[derive(Debug, Clone, Copy)]
enum Accessor {
    Controller,
    PriorityDriven,
    Driver,
    ControllerOf,
    PriorityDrivenOf,
    DriverOf,
}

impl Accessor {
    fn ask(self, answers: &Answers) -> String {
        match self {
            Accessor::Controller => format!("{:?}", answers.controller),
            Accessor::PriorityDriven => format!("{:?}", answers.priority_driven),
            Accessor::Driver => format!("{:?}", answers.driver),
            Accessor::ControllerOf => format!("{:?}", answers.controller_of),
            Accessor::PriorityDrivenOf => format!("{:?}", answers.priority_driven_of),
            Accessor::DriverOf => format!("{:?}", answers.driver_of),
        }
    }
}

/// Each read the reader census returns at this row's base, by enclosing function.
const READS: &[(&str, Accessor)] = &[
    ("resource::window_scope_from_cover_frames, prior frame", Accessor::Driver),
    ("resource::window_scope_from_cover_frames, current frame", Accessor::Driver),
    ("resource::window_cast_card_ids", Accessor::PriorityDriven),
    ("resource::window_cast_card_ids", Accessor::Controller),
    ("engine::reconcile_terminal_result", Accessor::Controller),
    ("engine::bounded_cycle_offer", Accessor::Driver),
    ("engine::apply_until_lethal_shortcut", Accessor::Driver),
    ("engine::until_lethal_fallback", Accessor::Controller),
    ("engine::materialize_fixed_shortcut", Accessor::Driver),
    ("engine::try_offer_object_growth_shortcut", Accessor::Controller),
    ("engine::try_offer_object_growth_shortcut", Accessor::PriorityDriven),
    ("engine::drive_persistent_axis_collapse", Accessor::DriverOf),
    ("engine::handle_declare_shortcut", Accessor::Driver),
    ("engine::handle_decline_shortcut", Accessor::Controller),
    (
        "engine::tests::a_trigger_driven_period_stops_at_the_producers_voluntariness_gate",
        Accessor::Controller,
    ),
    (
        "engine::tests::a_trigger_driven_period_stops_at_the_producers_voluntariness_gate",
        Accessor::PriorityDriven,
    ),
    (
        "engine::tests::a_resolving_minting_trigger_writes_against_the_accumulating_period, own",
        Accessor::Controller,
    ),
    (
        "engine::tests::a_resolving_minting_trigger_writes_against_the_accumulating_period, foreign",
        Accessor::Controller,
    ),
    ("engine::tests::signmix_offer_at_responder_beat", Accessor::Driver),
    ("game_state::reject_zero_bound_shortcut_offer", Accessor::Driver),
    ("game_state::GameState::loop_period_controller", Accessor::ControllerOf),
    ("game_state::GameState::loop_period_is_priority_driven", Accessor::PriorityDrivenOf),
    ("game_state::GameState::loop_period_driver", Accessor::DriverOf),
    ("game_state::loop_period_driver_of", Accessor::ControllerOf),
    ("game_state::loop_period_driver_of", Accessor::PriorityDrivenOf),
];

/// Beat cap for a frame drive; it bounds a runaway drive and is read by no assertion.
const FRAME_BEATS: usize = 400;

/// How many of the board's voluntary choices the declared drive accepts before it declines.
const ACCEPTS: usize = 9;

fn top_trigger_source(state: &GameState) -> Option<ObjectId> {
    match &state.stack.back()?.kind {
        StackEntryKind::TriggeredAbility { source_id, .. } => Some(*source_id),
        _ => None,
    }
}

/// CR 603.3b: Altar of the Brood's triggers are put on the stack last, so they resolve first.
pub(crate) fn altar_resolves_first(state: &GameState) -> Option<GameAction> {
    let WaitingFor::OrderTriggers { triggers, .. } = &state.waiting_for else {
        return None;
    };
    let (mut altar, mut order): (Vec<usize>, Vec<usize>) = (0..triggers.len())
        .partition(|&i| triggers[i].source_name.starts_with("Altar of the Brood"));
    order.append(&mut altar);
    Some(GameAction::OrderTriggers { order })
}

fn cast_animate_dead(runner: &mut GameRunner, animate_dead: ObjectId, target: ObjectId) {
    let card_id = runner.state().objects[&animate_dead].card_id;
    runner
        .act(GameAction::CastSpell {
            object_id: animate_dead,
            card_id,
            targets: vec![target],
            payment_mode: CastPaymentMode::Auto,
        })
        .expect("Animate Dead is castable from the built board");
}

/// Three consecutive windows of one board: each as the accessors read it, each as the cover sees
/// it once an offer there is declined, and the first window's record.
pub(crate) struct Frames {
    pub(crate) read: [GameState; 3],
    pub(crate) cover: [GameState; 3],
    pub(crate) record: Vec<LoopActionContext>,
}

/// Three consecutive windows at which `minting`'s trigger stands on top of the stack with a
/// non-empty record and P0 holds priority or is offered the loop, reached through `apply()` under
/// the board's declared drive. Each offer is declined once its frame is read.
fn capture_frames(
    runner: &mut GameRunner,
    minting: ObjectId,
    mut declared: impl FnMut(&GameState) -> Option<GameAction>,
) -> Frames {
    let (mut read, mut cover) = (Vec::new(), Vec::new());
    for _ in 0..FRAME_BEATS {
        let state = runner.state();
        let offer = matches!(
            state.waiting_for,
            WaitingFor::LoopShortcut { proposer, .. } if proposer == P0
        );
        let window = (offer
            || matches!(state.waiting_for, WaitingFor::Priority { player } if player == P0))
            && top_trigger_source(state) == Some(minting)
            && !state.last_loop_action_sequence.is_empty();
        if window {
            read.push(state.clone());
        }
        let action = offer
            .then_some(GameAction::DeclineShortcut)
            .or_else(|| altar_resolves_first(state))
            .or_else(|| declared(state))
            .unwrap_or_else(|| match state.waiting_for {
                WaitingFor::Priority { .. } => GameAction::PassPriority,
                _ => engine::ai_support::legal_actions(state)
                    .into_iter()
                    .find(|action| !matches!(action, GameAction::PassPriority))
                    .expect("a prompt the declared drive does not answer offers a legal action"),
            });
        if window && !offer {
            cover.push(state.clone());
        }
        runner
            .act(action.clone())
            .unwrap_or_else(|error| panic!("{action:?} was rejected: {error:?}"));
        if window && offer {
            cover.push(runner.state().clone());
        }
        if read.len() == 3 {
            let record = read[0].last_loop_action_sequence.clone();
            return Frames {
                read: read.try_into().expect("three frames"),
                cover: cover.try_into().expect("three frames"),
                record,
            };
        }
    }
    panic!(
        "the drive reached {} of three minting frames in {FRAME_BEATS} beats",
        read.len()
    );
}

/// Board A: Animate Dead returns Abdel Adrian, whose enters trigger exiles only Animate Dead
/// while accepts remain and then exiles nothing.
pub(crate) fn board_a_frames() -> Option<Frames> {
    let crate::abdel_adrian_animate_dead_altar_board::AbdelAnimateAltarBoard {
        mut runner,
        abdel,
        animate_dead,
        ..
    } = crate::abdel_adrian_animate_dead_altar_board::build()?;
    runner.state_mut().loop_detection = LoopDetectionMode::Interactive;
    let returned = runner.state().objects[&animate_dead].card_id;
    cast_animate_dead(&mut runner, animate_dead, abdel);
    let mut accepts = ACCEPTS;
    Some(capture_frames(&mut runner, abdel, move |state| {
        let WaitingFor::EffectZoneChoice { cards, .. } = &state.waiting_for else {
            return None;
        };
        let exiled = if accepts > 0 {
            accepts -= 1;
            cards
                .iter()
                .copied()
                .filter(|id| {
                    state
                        .objects
                        .get(id)
                        .is_some_and(|object| object.card_id == returned)
                })
                .collect()
        } else {
            Vec::new()
        };
        Some(GameAction::SelectCards { cards: exiled })
    }))
}

/// Board B: Animate Dead returns Felidar Guardian. Each Illusion's enters trigger targets the
/// original Felidar Guardian and accepts while accepts remain; the original's own enters trigger
/// targets Altar of the Brood and declines.
pub(crate) fn board_b_frames() -> Option<Frames> {
    let crate::loop_period_trigger_driven_arming::PrestonBoard {
        mut runner,
        felidar,
        animate_dead,
        preston,
        altar,
    } = crate::loop_period_trigger_driven_arming::build_board_b()?;
    cast_animate_dead(&mut runner, animate_dead, felidar);
    let mut accepts = ACCEPTS;
    Some(capture_frames(
        &mut runner,
        preston,
        move |state| match &state.waiting_for {
            WaitingFor::TriggerTargetSelection { .. } => {
                let aimed = if top_trigger_source(state) == Some(felidar) {
                    altar
                } else {
                    felidar
                };
                engine::ai_support::legal_actions(state)
                    .into_iter()
                    .find(|action| {
                        matches!(action, GameAction::ChooseTarget {
                            target: Some(TargetRef::Object(id)),
                        } if *id == aimed)
                    })
            }
            WaitingFor::OptionalEffectChoice { source_id, .. } => {
                let accept = *source_id != felidar && accepts > 0;
                if accept {
                    accepts -= 1;
                }
                Some(GameAction::DecideOptionalEffect { accept })
            }
            _ => None,
        },
    ))
}

fn assert_reads(board: &str, state: &GameState, expected: &Answers) {
    let actual = answers(state);
    for (site, accessor) in READS {
        assert_eq!(
            accessor.ask(&actual),
            accessor.ask(expected),
            "{board}: the read in {site} ({accessor:?}) moved"
        );
    }
}

#[test]
fn every_census_read_answers_on_the_blink_boards_and_a_restored_offer_as_at_the_base() {
    let trigger_driven = Answers {
        controller: Some(P0),
        priority_driven: false,
        driver: None,
        controller_of: Some(P0),
        priority_driven_of: false,
        driver_of: None,
    };
    let (Some(board_a), Some(board_b)) = (board_a_frames(), board_b_frames()) else {
        return;
    };
    for (frame, state) in board_a.read.iter().enumerate() {
        assert_reads(&format!("board A frame {frame}"), state, &trigger_driven);
    }
    for (frame, state) in board_b.read.iter().enumerate() {
        assert_reads(&format!("board B frame {frame}"), state, &trigger_driven);
    }

    let offer = crate::committed_dump_walk::restore_committed(
        &std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/combo_infinite_pile_4p_offer.json.gz"),
    )
    .expect("the committed offer restores");
    assert!(
        matches!(offer.waiting_for, WaitingFor::LoopShortcut { .. }),
        "the restored board keeps its record only at an offer"
    );
    assert_reads(
        "combo_infinite_pile_4p_offer at restore",
        &offer,
        &Answers {
            controller: Some(P0),
            priority_driven: true,
            driver: Some(P0),
            controller_of: Some(P0),
            priority_driven_of: true,
            driver_of: Some(P0),
        },
    );
}
