#!/usr/bin/env python3
"""trace_cluster.py — measured trace-keyed reclustering of unsupported cards.

Rationale (2026-07-03): the S07 tranche showed that grouping cards by the
PARSER CODE PATH a fix must touch (not by mechanic name / handler regex) is
what makes one class fix flip many cards at once, and that batching clusters
which share a hot parser file into serial "lanes" avoids merge conflicts.
This program MEASURES those properties instead of guessing them:

  measured inputs (all pre-existing tooling — reuse, don't reinvent):
    * data/coverage-data.json      — engine-authoritative per-card coverage:
                                     gap_details[{handler, source_text}] is the
                                     full, untruncated per-card gap membership.
                                     (Regenerated by scripts/gen-card-data.sh /
                                     the Tilt `card-data` resource.)
    * data/card-data.json          — object keyed by lowercased name;
                                     .value.legalities.<fmt> == "legal"
                                     (join contract documented + verified in
                                     .planning/coverage-analysis/coverage-breakdown.sh).
    * out/parser-gaps.json         — `cargo parser-gaps data/ > out/parser-gaps.json`
                                     = crates/engine/src/game/gap_analysis.rs
                                     analyze_gaps(): categories A–G, matched
                                     verbs, affected_cards, quick_wins. The
                                     A–D "near miss" categories are the
                                     engine's own cheap-fix classification.
    * crates/engine/src/parser/**  — live-grepped at runtime for handler
                                     literals / verb dispatch sites → emitting
                                     -file attribution with grep evidence
                                     (never hardcoded line numbers).

  new measurement added here (did not exist in-tree):
    * shape signature: gap source_text folded (numbers incl. number-words → N,
      mana symbols → {M}, self-name → ~, ws collapse) and truncated to a
      dispatch head — cards with the same head hit the same parser branch.
    * cross-pool overlap: same signature family present in both pools ⇒ one
      fix pays twice; measured, reported per cluster.
    * lane assignment: cluster families attributed to the same parser file
      form one serial lane (S07's serialization rule, operationalized).

Usage:
  trace_cluster.py --pool standard --pool modern+commander \
                   [--gaps out/parser-gaps.json] [--top 40]
  trace_cluster.py --selftest

Outputs (per pool tag, under out/<tag>/):
  trace-clusters.tsv   card ⇥ gap_count ⇥ handler ⇥ category ⇥ verb ⇥ shape_sig ⇥ family ⇥ file_attr
  trace-families.tsv   family ⇥ pool_count ⇥ xpool_count ⇥ category_mix ⇥ files ⇥ lane ⇥ score ⇥ example_cards
  plus out/cross-pool-overlap.tsv and a printed ranked summary.
"""

import argparse
import json
import re
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
COV = REPO / "data" / "coverage-data.json"
CARD = REPO / "data" / "card-data.json"
PARSER_SRC = REPO / "crates" / "engine" / "src" / "parser"
OUT = HERE / "out"

# ── pool definitions ────────────────────────────────────────────────────────
POOLS = {
    "standard": ["standard"],
    "modern+commander": ["modern", "commander"],  # intersection, per old plans
}

# ── shape signature folding (new measurement) ───────────────────────────────
NUMBER_WORDS = (
    "one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|"
    "fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|x"
)
RE_REMINDER = re.compile(r"\([^)]*\)")
RE_MANA = re.compile(r"\{[^}]{1,4}\}")
RE_NUM = re.compile(rf"\b(?:\d+|{NUMBER_WORDS})\b")
RE_DETECTOR_PREFIX = re.compile(r"^\[warning:[^\]]*\]\s*")
RE_LABEL_DASH = re.compile(r"^[A-Za-z_]+ — ")  # "Condition_If — "
SIG_HEAD_TOKENS = 8


# Per-detector dispatch anchors: the signature must center on the token the
# parser dispatches on, not on whatever line the swallowed fragment starts
# with (multi-line fragments often begin with an unrelated keyword line).
DETECTOR_ANCHORS = {
    "Condition_If": (" if ",),
    "Condition_AsLongAs": ("as long as",),
    "Condition_Unless": ("unless",),
    "Duration_UntilEndOfTurn": ("until end of turn",),
    "Duration_ThisTurn": ("this turn",),
    "Duration_NextTurn": ("next turn", "your next turn"),
    "DynamicQty": ("for each", "equal to", "where x", "that many"),
    "Optional_YouMay": ("you may",),
    "Optional_MayHave": ("may have", "you may"),
    "ActivateOnlyDuring": ("activate only",),
    "ActivateLimit": ("activate only", "no more than once"),
    "Replacement_Instead": ("instead",),
    "Modal_DynamicMaxDropped": ("choose",),
    "APNAP": ("each player", "each opponent"),
}
ANCHOR_BEFORE, ANCHOR_AFTER = 2, 8


def detector_of(handler: str) -> str:
    return handler.split(":", 1)[1] if handler.startswith("Swallow:") else ""


def anchor_window(folded: str, anchors) -> str:
    """Window the folded text around the first dispatch anchor found."""
    for a in anchors:
        i = folded.find(a)
        if i >= 0:
            toks = folded[:i].split(" ")
            start = max(0, len([t for t in toks if t]) - ANCHOR_BEFORE)
            words = folded.split(" ")
            alen = len(a.split(" "))
            return " ".join(words[start:start + ANCHOR_BEFORE + alen + ANCHOR_AFTER])
    return ""


def fold_clause(text: str, self_name: str = "", detector: str = "") -> str:
    """Fold a gap clause to its dispatch-shape signature."""
    s = text  # keep the WHOLE fragment; anchoring picks the dispatch site
    s = RE_DETECTOR_PREFIX.sub("", s)
    s = RE_LABEL_DASH.sub("", s)
    s = s.replace("\n", " / ")
    if self_name:
        s = s.replace(self_name, "~")
        first = self_name.split(",")[0].strip()
        if len(first) > 3:
            s = s.replace(first, "~")
    s = s.lower()
    s = RE_REMINDER.sub(" ", s)
    s = RE_MANA.sub("{M}", s)
    s = re.sub(r"(\{M\})+", "{M}", s)  # a cost's symbol count is a leaf param, not shape
    s = RE_NUM.sub("N", s)
    s = re.sub(r"[’']", "'", s)
    s = re.sub(r"\s+", " ", s).strip().rstrip(".")
    if detector:
        w = anchor_window(s, DETECTOR_ANCHORS.get(detector, ()))
        if w:
            return w
    return s


def sig_head(sig: str, k: int = SIG_HEAD_TOKENS) -> str:
    return " ".join(sig.split(" ")[:k])


# ── handler → parser-file attribution (live grep, evidence attached) ────────
# Swallow detectors are HONEST-FAILURE markers from swallow_check.rs; the FIX
# site is the single-authority combinator that should learn the clause. That
# single-authority table is workspace doctrine (CLAUDE.md / oracle-parser
# skill: parse_inner_condition is the one authority for game-state conditions,
# duration.rs for durations, quantity.rs for quantities). Encoded here as
# detector → authority-module hints; the grep step attaches concrete evidence.
SWALLOW_AUTHORITY = {
    "Condition_If": "oracle_nom/condition.rs",
    "Condition_AsLongAs": "oracle_nom/condition.rs",
    "Condition_Unless": "oracle_nom/condition.rs",
    "Duration_UntilEndOfTurn": "oracle_nom/duration.rs",
    "Duration_ThisTurn": "oracle_nom/duration.rs",
    "Duration_NextTurn": "oracle_nom/duration.rs",
    "DynamicQty": "oracle_quantity.rs",
    "Optional_YouMay": "oracle_effect/",
    "Optional_MayHave": "oracle_static.rs",
    "ActivateOnlyDuring": "oracle_casting.rs",
    "ActivateLimit": "oracle_casting.rs",
    "Replacement_Instead": "oracle_effect/",
    "Modal_DynamicMaxDropped": "oracle_effect/sequence.rs",
    "APNAP": "oracle_trigger.rs",
}


def canon_attr(path: str) -> str:
    """One canonical spelling per file so lane keying never splits on form."""
    p = path.replace("crates/engine/src/", "")
    return p if p.startswith(("parser/", "engine-runtime", "UNATTRIBUTED")) else p


def grep_evidence(literal: str, max_hits: int = 3):
    """Live grep for a handler literal in parser source; returns file hits."""
    try:
        r = subprocess.run(
            ["grep", "-rln", "--include=*.rs", literal, str(PARSER_SRC)],
            capture_output=True, text=True, timeout=30,
        )
        files = [
            str(Path(p).relative_to(REPO)) for p in r.stdout.splitlines()
            if "/tests" not in p and "_tests.rs" not in p
        ]
        return files[:max_hits]
    except Exception:
        return []


def attribute_handler(handler: str, grep_cache: dict) -> tuple:
    """(file_attr, basis). Cached live-grep + doctrine table."""
    if handler in grep_cache:
        return grep_cache[handler]
    attr, basis = "UNATTRIBUTED", "none"
    if handler.startswith("Swallow:"):
        det = handler.split(":", 1)[1]
        hint = SWALLOW_AUTHORITY.get(det)
        if hint:
            attr, basis = f"parser/{hint}", "single-authority doctrine"
        ev = grep_evidence(f'"{det}"')
        if ev:
            basis += f" + grep:{';'.join(ev)}"
    elif handler.startswith("Trigger:"):
        phrase = handler.split(":", 1)[1][:40]
        ev = grep_evidence(phrase.lower()) or grep_evidence(phrase)
        if ev:
            attr, basis = ev[0], "grep-literal"
        else:
            attr, basis = "parser/oracle_trigger.rs", "trigger-dispatch default"
    elif handler.startswith("Effect:"):
        tag = handler.split(":", 1)[1]
        if re.fullmatch(r"\{\d+\}", tag):
            attr, basis = "parser/oracle_effect/", "chain-positional (imperative dispatch)"
        else:
            ev = grep_evidence(f'"{tag}"')
            if ev:
                attr, basis = ev[0], "grep-literal"
            else:
                attr, basis = "parser/oracle_effect/", "verb-dispatch default"
    elif handler.startswith("Cost:") or "KeywordCost" in handler:
        attr, basis = "parser/oracle_casting.rs", "cost-dispatch default"
    elif handler.startswith("ParseWarning:"):
        tag = handler.split(":", 1)[1]
        if "target" in tag:
            attr, basis = "parser/oracle_target.rs", "target-fallback family"
        else:
            ev = grep_evidence(f'"{tag}"')
            attr, basis = (ev[0], "grep-literal") if ev else (
                "parser/oracle.rs", "warning default")
    attr = canon_attr(attr)
    grep_cache[handler] = (attr, basis)
    return attr, basis


# ── resolver-flagged (gap_count==0) runtime families ─────────────────────────
# Ported verbatim-in-spirit from cluster-assign.sh's R-rules (provenance:
# .planning/coverage-analysis/cluster-assign.sh) — these 5 rules were sound;
# they classify RUNTIME work where no parser trace exists.
def runtime_family(oracle: str) -> str:
    lo = oracle.lower()
    if re.search(r"start your engines|max speed", lo):
        return "R1-speed-mechanic"
    if "level up" in lo:
        return "R3-level-up"
    if "as long as" in lo:
        return "R2-aslongas-conditional-static"
    if re.search(r"can.?t (attack|block|be|have|cast|activate)", lo):
        return "R4-cant-restriction-static"
    return "R5-runtime-bespoke"


# ── scoring ──────────────────────────────────────────────────────────────────
# Rank basis (all measured, printed alongside the rank so readers see why):
#   pool_count      cards in this pool the family covers
#   xpool_count     cards in the OTHER pool sharing the family (shared fix)
#   near_miss_share fraction of members in analyzer categories A–D (cheap)
# score = (pool + 0.5*xpool) * (0.5 + near_miss_share)  — near-miss-heavy
# families rank up; F/G/R-heavy families rank down but are never dropped
# (all-cards-must-ship policy is unchanged).
def family_score(pool_n: int, xpool_n: int, near_share: float) -> float:
    return (pool_n + 0.5 * xpool_n) * (0.5 + near_share)


# ── main pipeline ────────────────────────────────────────────────────────────
def load_pools(card_path: Path):
    data = json.loads(card_path.read_text())
    pools = {tag: set() for tag in POOLS}
    for _k, v in data.items():
        name = v.get("name")
        leg = v.get("legalities") or {}
        if not name:
            continue
        for tag, fmts in POOLS.items():
            if all(leg.get(f) == "legal" for f in fmts):
                pools[tag].add(name)
    return pools


def load_gap_index(gaps_path: Path):
    """card → (category, verb) from analyzer affected_cards (untruncated)."""
    idx = {}
    if not gaps_path or not gaps_path.exists():
        return idx
    g = json.loads(gaps_path.read_text())
    for cat_label, summ in (g.get("categories") or {}).items():
        for c in summ.get("affected_cards") or []:
            idx.setdefault(c, (cat_label, None))
        for vb in summ.get("by_verb") or []:
            for c in vb.get("affected_cards") or []:
                idx[c] = (cat_label, vb.get("verb"))
    return idx


def run(pool_tags, gaps_path, top, cov_path=COV, card_path=CARD):
    cov = json.loads(cov_path.read_text())
    pools = load_pools(card_path)
    gap_idx = load_gap_index(gaps_path)
    grep_cache = {}

    stamp = {}
    rows_by_pool = {t: [] for t in pool_tags}
    fam_members = defaultdict(lambda: defaultdict(set))  # family → pool → cards
    fam_meta = defaultdict(lambda: {"files": Counter(), "cats": Counter(),
                                    "handlers": Counter(), "sigs": Counter()})

    for card in cov["cards"]:
        if card.get("supported"):
            continue
        name = card["card_name"]
        in_pools = [t for t in pool_tags if name in pools.get(t, ())]
        if not in_pools:
            continue
        gap_count = card.get("gap_count", 0)
        cat, verb = gap_idx.get(name, ("", None))
        if gap_count == 0:
            fam = runtime_family(card.get("oracle_text") or "")
            sig = fam
            handler, attr, basis = "resolver-flagged", "engine-runtime", "R-rule"
            fams = [(fam, sig, handler, attr)]
        else:
            fams = []
            for gd in card.get("gap_details") or []:
                handler = gd.get("handler", "?")
                sig = fold_clause(gd.get("source_text") or "", name,
                                  detector_of(handler))
                head = sig_head(sig)
                attr, basis = attribute_handler(handler, grep_cache)
                fam = f"{handler}::{head}" if head else handler
                fams.append((fam, sig, handler, attr))
        for fam, sig, handler, attr in fams:
            m = fam_meta[fam]
            m["files"][attr] += 1
            m["cats"][cat or ("R" if gap_count == 0 else "?")] += 1
            m["handlers"][handler] += 1
            m["sigs"][sig] += 1
            for t in in_pools:
                fam_members[fam][t].add(name)
                rows_by_pool[t].append(
                    (name, gap_count, handler, cat, verb or "", sig, fam, attr))

    # lane assignment: families sharing a primary file → one lane
    lane_of_file, lanes = {}, defaultdict(list)
    fam_rank = {}
    for fam, per_pool in fam_members.items():
        primary_file = fam_meta[fam]["files"].most_common(1)[0][0]
        lane = lane_of_file.setdefault(primary_file, f"L{len(lane_of_file)+1:02d}")
        lanes[lane].append(fam)
        near = sum(n for c, n in fam_meta[fam]["cats"].items()
                   if c[:1] in "ABCD") / max(1, sum(fam_meta[fam]["cats"].values()))
        for t in pool_tags:
            n = len(per_pool.get(t, ()))
            x = max((len(per_pool.get(o, ())) for o in pool_tags if o != t), default=0)
            if n:
                fam_rank[(t, fam)] = (family_score(n, x, near), n, x, near,
                                      primary_file, lane)

    OUT.mkdir(exist_ok=True)
    for t in pool_tags:
        d = OUT / t
        d.mkdir(parents=True, exist_ok=True)
        with open(d / "trace-clusters.tsv", "w") as f:
            for r in sorted(rows_by_pool[t]):
                f.write("\t".join(str(x) for x in r) + "\n")
        fams = sorted(((s, fam) for (pt, fam), (s, *_r) in fam_rank.items()
                       if pt == t), reverse=True)
        with open(d / "trace-families.tsv", "w") as f:
            f.write("family\tpool_count\txpool_count\tnear_miss_share\t"
                    "primary_file\tlane\tscore\texamples\n")
            for s, fam in fams:
                _s, n, x, near, pf, lane = fam_rank[(t, fam)]
                ex = "; ".join(sorted(fam_members[fam][t])[:4])
                f.write(f"{fam}\t{n}\t{x}\t{near:.2f}\t{pf}\t{lane}\t{s:.1f}\t{ex}\n")
        stamp[t] = {"unsupported_rows": len(rows_by_pool[t]),
                    "families": len(fams)}
        print(f"\n== {t}: top {top} trace families "
              f"({len(fams)} families, {len({r[0] for r in rows_by_pool[t]})} cards) ==")
        for s, fam in fams[:top]:
            _s, n, x, near, pf, lane = fam_rank[(t, fam)]
            print(f"  {s:7.1f}  n={n:<4} xpool={x:<4} near={near:.2f} "
                  f"{lane} {pf:<44} {fam[:70]}")

    # lane rollup = tranche seeds (S07 model: one lane ≈ one serialized batch
    # of work against a shared hot parser file; lanes are mutually parallel)
    for t in pool_tags:
        lane_cards = defaultdict(set)
        lane_files = defaultdict(Counter)
        lane_fams = defaultdict(list)
        for (pt, fam), (s, n, x, near, pf, lane) in fam_rank.items():
            if pt != t or not fam_members[fam].get(t):
                continue
            lane_cards[lane] |= fam_members[fam][t]
            lane_files[lane][pf] += n
            lane_fams[lane].append((s, fam, n))
        with open(OUT / t / "lane-rollup.tsv", "w") as f:
            f.write("lane\tcards\tprimary_file\tfamilies\ttop_families\n")
            print(f"\n== {t}: lane rollup (tranche seeds) ==")
            for lane, cards in sorted(lane_cards.items(),
                                      key=lambda kv: -len(kv[1])):
                pf = lane_files[lane].most_common(1)[0][0]
                fams_l = sorted(lane_fams[lane], reverse=True)
                tops = " | ".join(f"{fam.split('::')[-1][:38]}×{n}"
                                  for _s, fam, n in fams_l[:3])
                f.write(f"{lane}\t{len(cards)}\t{pf}\t{len(fams_l)}\t{tops}\n")
                print(f"  {lane}  {len(cards):4d} cards  {len(fams_l):3d} fams  "
                      f"{pf:<40} {tops[:70]}")

    with open(OUT / "cross-pool-overlap.tsv", "w") as f:
        f.write("family\t" + "\t".join(pool_tags) + "\n")
        for fam, per_pool in sorted(fam_members.items()):
            counts = [len(per_pool.get(t, ())) for t in pool_tags]
            if sum(1 for c in counts if c) > 1:
                f.write(fam + "\t" + "\t".join(map(str, counts)) + "\n")
    print(f"\nwrote out/<pool>/trace-clusters.tsv, trace-families.tsv, "
          f"out/cross-pool-overlap.tsv  · stamp: {json.dumps(stamp)}")


# ── selftest (non-vacuous: discriminates folding + grouping) ────────────────
def selftest():
    a = fold_clause("Condition_If — You may pay {B} rather than pay this "
                    "spell's mana cost if there are thirteen or more creatures "
                    "on the battlefield.", "Blasphemous Edict")
    b = fold_clause("Condition_If — You may pay {2}{R} rather than pay this "
                    "spell's mana cost if there are seven or more creatures on "
                    "the battlefield.", "Other Card")
    assert a == b, f"same-shape clauses must fold identically:\n {a}\n {b}"
    c = fold_clause("Condition_If — if it was kicked, exile it.", "X")
    assert a != c, "different dispatch shapes must NOT collide"
    assert sig_head("a b c d e f g h i j") == "a b c d e f g h"
    assert runtime_family("As long as you control ...") == \
        "R2-aslongas-conditional-static"
    assert runtime_family("Start your engines!") == "R1-speed-mechanic"
    d = fold_clause("Whenever ~ attacks, draw two cards.", "Foo, the Bar")
    assert "N" in d and "~" in d
    # anchoring: a multi-line fragment starting with a keyword line must
    # center its signature on the detector's dispatch token, not "menace"
    e = fold_clause("Condition_If — Menace\nAt the beginning of your end "
                    "step, if an opponent lost life this turn, draw a card.",
                    "X", "Condition_If")
    assert e.startswith(("end step, if", "your end step, if")) or " if " in e[:20], e
    assert "menace" not in e, f"anchor failed, keyword line leaked: {e}"
    f2 = fold_clause("Condition_If — Menace\nAt the beginning of combat, if "
                     "an opponent lost life this turn, scry 1.",
                     "Y", "Condition_If")
    # two different hosts, same dispatch shape → same-ish anchored window family
    assert ("if an opponent lost life this turn" in e
            and "if an opponent lost life this turn" in f2)
    print("selftest OK")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--pool", action="append", choices=list(POOLS),
                    help="repeatable; default: both")
    ap.add_argument("--gaps", type=Path, default=OUT / "parser-gaps.json")
    ap.add_argument("--top", type=int, default=40)
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        selftest()
        sys.exit(0)
    run(args.pool or list(POOLS), args.gaps, args.top)
