# Source before every cargo command in run dandan-5169 (small box: 4 cores, 15 GB RAM, ~38 GB disk).
export CARGO_BUILD_JOBS=2 CARGO_INCREMENTAL=0 CARGO_PROFILE_DEV_DEBUG=0 CARGO_PROFILE_TEST_DEBUG=0 CARGO_PROFILE_TOOL_DEBUG=0 MTGJSON_SKIP_REFRESH=1
